### ISSUE TITLE
[BUG] calculate density matrix

### ISSUE THREAD

**Issue by Jaikinator** [diffqc/dqc#1]
Normally, for example in pyscf the density Matrix P is defined by the expansion coefficient Matrix.  
So the trace of P*S (where S is the overlap Matrix) should be equal to the number of Electrons in the system. 
When I try your density Matrix given by the code below, the trace of the density Matrix itself result in the number of electrons.
So, can you explain to me why you use it like this?

**The Program**
`basis = [dqc.loadbasis("1:3-21G"), dqc.loadbasis("1:3-21G")]`
`atomstruc = "H 1 0 0; H -1 0 0"`
`m = dqc.Mol(atomstruc, basis = basis)`
`qc = dqc.HF(m).run()`
`dm = qc.aodm()`
`print(torch.trace(dm)) #gives 2 in this example`

**Desktop (please complete the following information):**
 - DQC version: 0.1.0
 - Python version:  3.8.1
 - PyTorch version: 1.9
 - OS: Ubuntu

**Comment by mfkasim1** [comment]
The density matrix used in DQC is not the same as density matrix in PySCF, as DQC is using orthogonalized gaussian basis.
If using gaussian basis (like PySCF), the Roothaan's equation is

    FC = SCE

Where F is the Fock matrix, C is the orbital matrix, S is the orbital matrix, and E is the diagonal matrix containing the orbital energies. What we did is we orthogonalize the equation above by multiplying `S^(-0.5)` from left and defining `C=S^(-0.5)C'` with `C'` is the new orbital matrix in the orthogonalize basis. So the equation becomes

    F'C' = C'E

with `F'=(S^(-0.5) F S^(-0.5))`, so the relation between DQC density matrix (`P'`) and PySCF density matrix (`P`) is

    P = S^(-0.5) P' S^(-0.5).

With those relations, we can write

    tr(PS) = tr(S^(-0.5) P' S^(0.5)) = tr(P')

**Comment by mfkasim1** [comment]
To get the same behaviour with PySCF, you need to add `orthogonalize_basis=False` in Mol, so

    m = dqc.Mol(atomstruc, basis = basis, orthogonalize_basis=False)

**Comment by Jaikinator** [comment]
> To get the same behaviour with PySCF, you need to add `orthogonalize_basis=False` in Mol, so
> 
> ```
> m = dqc.Mol(atomstruc, basis = basis, orthogonalize_basis=False)
> ```

If I try to use this, I got the following error:
`TypeError: __init__() got an unexpected keyword argument 'orthogonalize_basis'`

And I as well do not find any description in the Mol Class where this should be defined. I haven't changed anything else than to modify the specific line.

**Comment by mfkasim1** [comment]
Ah, sorry, it is still in the nightly version. Can you install it from github?

**Comment by Jaikinator** [comment]
> Ah, sorry, it is still in the nightly version. Can you install it from github?

Yes, I update it to dqc-0.2.0, and it works. Thank you very much.
