### ISSUE TITLE
[ENH] Will dqc support a solid system with externel potentials?

### ISSUE THREAD

**Issue by floatingCatty** [diffqc/dqc#4]
Like implementing Pseudopotential approximation.

**Comment by mfkasim1** [comment]
There is an experimental feature (undocumented) on solid system with gaussian basis using density fitting. However, the 3-centre integrals are very slow and I'm not sure if it propagates the gradient, so it is not ready yet.
We certainly have a plan to expand it to solid system, but currently it is not our top priority. If you want to make a pull request on solid system, you are welcome to do so.
