### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ml-electron-project** [diffqc/dqc#5]
I tried to run the customized meta-GGA functional by setting dqc.xc.CustomXC.family =4, but it did not work. 
This is the code:

```

import torch
import dqc
import torch
import dqc.xc
import dqc.utils

class MyXC(dqc.xc.CustomXC):
    def __init__(self):
        super().__init__()

    @property
    def family(self):
        # 1 for LDA, 2 for GGA, 4 for MGGA
        return 4

    def get_edensityxc(self, densinfo):
        scan = dqc.get_xc("MGGA_X_SCAN + MGGA_C_SCAN")
        return scan.get_edensityxc(densinfo)


myxc = MyXC()


atomzs, atomposs = dqc.parse_moldesc("H -1 0 0; H 1 0 0")
atomposs = atomposs.requires_grad_()  # mark atomposs as differentiable
mol = dqc.Mol((atomzs, atomposs), basis="6-311++G(3df,3pd)")
qc = dqc.KS(mol, xc=myxc, variational=False).run()

```

Then I got the following error message:

> Traceback (most recent call last):
>   File "test_customxc.py", line 29, in <module>
>     qc = dqc.KS(mol, xc=myxc, variational=False).run()
>   File "/usr/local/lib/python3.8/dist-packages/dqc/qccalc/scf_qccalc.py", line 90, in run
>     scp0 = self._engine.dm2scp(dm)
>   File "/usr/local/lib/python3.8/dist-packages/dqc/qccalc/ks.py", line 116, in dm2scp
>     return self.__dm2fock(dm).fullmatrix()
>   File "/usr/local/lib/python3.8/dist-packages/dqc/qccalc/ks.py", line 177, in __dm2fock
>     vxc = self.hamilton.get_vxc(dm)  # spin param or tensor (..., nao, nao)
>   File "/usr/local/lib/python3.8/dist-packages/dqc/hamilton/hcgto.py", line 236, in get_vxc
>     potinfo = self.xc.get_vxc(densinfo)  # value: (*BD, nr)
>   File "/usr/local/lib/python3.8/dist-packages/dqc/xc/base_xc.py", line 96, in get_vxc
>     raise NotImplementedError("Default vxc for family %d is not implemented" % self.family)
> NotImplementedError: Default vxc for family 4 is not implemented

 - DQC version: 0.1.0
 - Python version: 3.3
 - PyTorch version: 1.10.1
 - OS: Ubuntu 20.04 LTS

**Comment by mfkasim1** [comment]
Thanks for the detailed error message. I have pushed a fix just now, so please use that one. You can install it via
```
python -m pip uninstall dqc
git clone https://github.com/diffqc/dqc
cd dqc
python -m pip install -e .
```

**Comment by ml-electron-project** [comment]
Thank you for quick response. It worked!
